name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Unit Tests
        run: make unittest
      - name: Run e2e
        run: make run-e2e